### ISSUE TITLE
Personal info in makefile with latest commit?

### ISSUE THREAD

**Issue by urherenow** [badda71/vice3ds#1]
"INSTDIR = /c/Users/seweber/AppData/Roaming/Citra/sdmc/3ds/vice3ds"

Why? If seweber is your every-day user name, making it publicly known is bad juju...

**Comment by badda71** [comment]
Hi,thanks for the notice. However, what could you possibly gain from knowing this?
Best regards,Sebastian

      Von: urherenow <notifications@github.com>
 An: badda71/vice3ds <vice3ds@noreply.github.com> 
CC: Subscribed <subscribed@noreply.github.com>
 Gesendet: 17:14 Freitag, 5.April 2019
 Betreff: [badda71/vice3ds] Personal info in makefile with latest commit? (#1)
   
"INSTDIR = /c/Users/seweber/AppData/Roaming/Citra/sdmc/3ds/vice3ds"Why? If seweber is your every-day user name, making it publicly known is bad juju...—

**Comment by urherenow** [comment]
Knowing your user name makes it a lot easier to break into your system. Not that I would, but I’m just saying, it’s something you shouldn’t make public. If you really want that function in your makefile, I would suggest using a variable instead and setting it like “make install user=xxx”. I would also delete this very issue.

Just trying to look out. I’m super stoked that you did this project though. Best. C64 emulator. Ever. And it’s not even a final release yet!
