### ISSUE TITLE
Downloading gamebase64 database file crashes n3ds

### ISSUE THREAD

**Issue by RandomMan25XX** [badda71/vice3ds#10]
No matter how I go about it in the latest version, trying to download the gamebase64 database file always leads to a crash, and after said crash if you re-attempt to use the gamebase64 option again it just keeps crashing, rendering the feature useless in the latest release of vice3ds

**Comment by badda71** [comment]
O3DS or N3DS?

**Comment by RandomMan25XX** [comment]
N3ds

**Comment by badda71** [comment]
I cannot replicate the issue - it sounds like a corrupted download. Please delete file /3ds/vice3DS-C64/default/gb64_2.db and try again ...

**Comment by RandomMan25XX** [comment]
I've deleted it three and yet it still happens, I've even nuked the entire setup and reinstalled the emulator, every single time it just gets to 96% and then just crashes the system, this only started happening on the latest version

**Comment by RandomMan25XX** [comment]
Deleting the whole folder (rip my downloads) solved the issue

**Comment by badda71** [comment]
ok, happy to hear that :-) Did you backup you games folder before deleting it? I would really like to replicate the issue ...

**Comment by RandomMan25XX** [comment]
I didn't, just said screw it and nuked the whole folder, aside from the gamebase64 database not downloading and crashing the system I couldn't even get into my games

**Comment by badda71** [comment]
ok, wonder if anybody else has the same issue ...

**Comment by badda71** [comment]
Fixed with commit 8e04d46
