### ISSUE TITLE
Appcrash many Gamebase64 titles?

### ISSUE THREAD

**Issue by grimson73** [badda71/vice3ds#11]

**Comment by grimson73** [comment]
Hello,
On my 2 N3DSXL's the app crashes when opening when (I suppose) download many titles from the Gamebase64 website.
 
Latest 3dsx version (v2.4)
Luma3DS v10.1.3-3a0418e2
Homebrew launcher v2.1.1

[AppCrash.zip](https://github.com/badda71/vice3ds/files/4718496/AppCrash.zip)

I tried:
- gba_2.db
Deleting gba_2.db from the vice-3DS-C64/default folder.
When I start the app and press start -> Gamebase64 db not found, download? -> yes
After downloading 'An exception occured'
Restarting the app and pressing + to access Gamebase64 -> crash

[Dump2.zip](https://github.com/badda71/vice3ds/files/4718559/Dump2.zip)

- cache folder
Deleted the 'cache' directory (kept the gba_2.db), restarting app -> crash
 
- games folder
Renaming the games folder solves it (for now) but will eventually reappear.

[games.zip](https://github.com/badda71/vice3ds/files/4718703/games.zip)


I was downloading the 469 most popular games while this occurs .. on both N3dsxl's .. also on earlier versions.

anyway thanks for developing this app!!

**Comment by badda71** [comment]
I think, I found the bug. Can you check with this version?
[vice3DS-C64.zip](https://github.com/badda71/vice3ds/files/4719212/vice3DS-C64.zip)

**Comment by grimson73** [comment]
> I think, I found the bug. Can you check with this version?
> [vice3DS-C64.zip](https://github.com/badda71/vice3ds/files/4719212/vice3DS-C64.zip)

Thank you! this seems to work!

**Comment by badda71** [comment]
Fixed with commit https://github.com/badda71/vice3ds/commit/8e04d46fc1cf1ae8dda6fde6068addf3670d8e56
