### ISSUE TITLE
Gamebase search issue

### ISSUE THREAD

**Issue by gingerbeardman** [badda71/vice3ds#13]
It's not possible to find this game (crossroads ii - pandemonium) with the in-emulator gamebase browser http://www.gamebase64.com/game.php?id=1824&d=18&h=0

Searching "crossroads"

**Comment by badda71** [comment]
I cannot reproduce the issue. List filter must be cleared (not "Popular" or "Downloaded"). 
![grafik](https://user-images.githubusercontent.com/11392517/102988441-307b9500-4514-11eb-97c4-691555a4568c.png)

**Comment by gingerbeardman** [comment]
I think that must be it! 

I'll clear my list, thanks.
