### ISSUE TITLE
EZFlash and GMod2 saves - how do they work?

### ISSUE THREAD

**Issue by wbovela** [badda71/vice3ds#14]
I am trying to get saves for either one of the cartridge types working for Metal Warrior Ultra. I have enabled eeprom and flash writes for GMod2 but saving to a save-slot in-game does nothing. Should I be mounting something as a flash-image?

EZFlash saves don't appear to save anything either.

Is there anything I should be doing to make saves work?

**Comment by badda71** [comment]
That functionality was not changed in Vice3DS as compared to standard Vice. Can you please check how and if it works on a PC (e.g. with Vice for Windows). If it works there, try to do the same with Vice3DS. If Vice3DS does not work but Vice works, please write the steps to reproduce the issue here.

**Comment by wbovela** [comment]
I will try that when I get home and report back.

Op ma 18 jul. 2022 om 12:03 schreef badda71 ***@***.***>:

**Comment by wbovela** [comment]
Well, I tried it with the ezflash cartridge on Vice3.6.1 and on 3dsVice and they both work fine.
I don't know what happened yesterday...case closed.
Sorry for the red herring.

**Comment by wbovela** [comment]
ezflash saving works fine. I must have made a mistake during the initial tests.
