### ISSUE TITLE
Vice3ds only exits gracefully from Vice menu

### ISSUE THREAD

**Issue by urherenow** [badda71/vice3ds#4]
If you open the menu and "quit emulator", everything is fine. If you use the home button then close the homebrew channel with X, the system hangs.

**Comment by badda71** [comment]
Uh, right ... I did not include any code that runs when the system requests a program exit. Need to do some research on how to do this with ctrulib ...

**Comment by badda71** [comment]
fixed with commit 0793f04cac571edd47195319d91a312c5ecfba81
