### ISSUE TITLE
Latest commits do not work on hardware

### ISSUE THREAD

**Issue by urherenow** [badda71/vice3ds#6]
.3dsx crashes back to HBC, .cia crashes back to home menu, .3ds doesn't even mount (and in fact, only shows up with a white box and file name in the Gateway rom selection menu). Config files never get extracted.

**Comment by badda71** [comment]
Not just hardware - the 3dsx was crashing in Citra as well :-(
There was a typo in the Makefile, this is fixed - but .cia and .3ds still don't work.

**Comment by urherenow** [comment]
I'm quite sure it has everything to do with the config files. How does vice3ds know where to extract them to or even read from/write to them, for that matter? I don't see how archdep_user_config_path() is getting the path, or why you would want a function to do that (other than the fact that you seem to like to test things on citra). The path should be static and absolute.

EDIT: but the (now working) .3dsx file does indeed extract the config files... but using the .cia version in Luma3ds (yay for error screens!) shows the crash to be on a read function.

**Comment by badda71** [comment]
Ok, here is the logic: I'm NOT writing to romfs. I'm only copying the config files from romfs to /3ds/vice3ds/config (if they do not already exist). Everything else is unchanged. The default config dir is still /3ds/vice3ds/config
Hope that clarifies. The error seems somewhere else. I just got the CIA and 3DS working in Citra (which they did not before). It was something deep inside original vice code - I believe vice has some flaws and the 3DS is not taking them gracefully.
Btw, I don't "like" to test in Citra, it is a necessity so save time. Testing in Citra just requires me to double click the 3dsx/3ds/cia file. Testing on hardware sucks: It takes forever to upload the cia, install it with FBI, start it and when it crashes, the reboot takes forever. Apart from the fact that there is no debug log on hardware - in Citra there is.

**Comment by vaguerant** [comment]
Just FYI, @badda71, if you use the Homebrew Launcher it's much easier to test new builds on hardware compared to CIA. The Homebrew Launcher includes a netloader; if you press the Y button, the 3DS will wait for a (3dsx) binary to come in over the network via 3dslink. It will also tell you your 3DS's IP address for convenience.

If you used the devkitPro installer on Windows, you will already have 3dslink set up. The default path on Windows is `C:\devkitPro\tools\bin\3dslink.exe`--if you installed to a custom path or are on another OS you're probably capable enough of finding the equivalent. :)

Usage is simple, just `3dslink vice3ds.3dsx -a X.X.X.X` (fill in your own IP) should have you up and running within seconds of compiling a new build. You can also just throw that into a batch/shell/etc. script depending on your platform so you can double click and go.

**Comment by badda71** [comment]
Thanks for the hint. I noticed however, that cia and 3dsx behave differently (somehow the homebrew launcher seems to take errors more gracefully as compared to running directly from home menu). Also, I really miss some kind of debug output when running on hardware and not having the option to choose one of the screens as console ...

**Comment by vaguerant** [comment]
Fair enough. Technically Rosalina (built into Luma3DS) does support debugging remotely with GDB or IDA Pro; they have info on it [here](https://github.com/AuroraWright/Luma3DS/wiki/Rosalina#gdb-stub), but I'm sure things are a lot more convenient in Citra.

**Comment by badda71** [comment]
yes, the GDB-stub in Rosalina is pretty cool - without it, I would not have found the bug in libSDL. But even GBD won't let me print messages to the GDB console while the code is running. Would be great if Rosalina had a debug logging thing like Citra - some server that I can start in Rosalina, then telnet to from my PC and then see the debug messages ... *dreaming* ;-)
