### ISSUE TITLE
Please revert the buildsystem

### ISSUE THREAD

**Issue by WinterMute** [badda71/vice3ds#7]
We've had many issues with people using that "buildtools" thing and we'd appreciate it if you didn't use it. While it may "work" for you it's not a build system we support because it simply doesn't work at all on some OS/processor combinations and in several cases we've resolved code not working on hardware by simply replacing it with a standard devkitPro makefile.

We'd also appreciate it if you didn't refer to devkitPro as if we're software  - we're the organisation who maintain the tools not a software package.

**Comment by WinterMute** [comment]
Actually, after doing a bit more research I found that the original code uses autotools based build system. It would be way better for everyone if that were modified to build 3ds code rather than plugging in a custom build system. If you're interested I can probably help with doing that.

**Comment by badda71** [comment]
> We've had many issues with people using that "buildtools" thing and we'd appreciate it if you didn't use it. While it may "work" for you it's not a build system we support because it simply doesn't work at all on some OS/processor combinations and in several cases we've resolved code not working on hardware by simply replacing it with a standard devkitPro makefile.

I would love to replace buildtools, but your standard devkitPro makefile does not build .cia or .3ds files. Or am I looking at the wrong file ... ?

> We'd also appreciate it if you didn't refer to devkitPro as if we're software - we're the organisation who maintain the tools not a software package.

I'm not aware of any place I refer to devkitPro as software. Maybe you could point me in the right direction.

> Actually, after doing a bit more research I found that the original code uses autotools based build system. It would be way better for everyone if that were modified to build 3ds code rather than plugging in a custom build system. If you're interested I can probably help with doing that.

Correct, original vice is using autotools - which I have to admit, I have not a lot of experience with. However, any help to make vice3DS better (or even integrate into the mainstream vice distribution) is highly appreciated!

**Comment by badda71** [comment]
No feedback received received on my comment that standard devkitPro makefile does not build .cia or .3ds files. Closing issue.

**Comment by WinterMute** [comment]
A ping would have helped rather than closing :p I hadn't seen the reply, sorry - buried in my inbox somewhere until it resurfaced when you closed.

.3ds files aren't relevant to homebrew and ideally homebrew shouldn't be distributed as .cia. There are advantages to 3dsx - not being tied to a single console, having the path to 3dsx available and allowing command line parameters. The latter two are obviously rather useful for emulators.

Ultimately though I think it's going to be better to teach the autotools system to build .3dsx here. Do you use IRC or Discord by any chance? It might be better to try & sort something realtime if possible rather than back & forward on here.

> I'm not aware of any place I refer to devkitPro as software. Maybe you could point me in the right direction

You've made reference to "devkitpro w/ devkitARM" which should just be "devkitARM" (provided by devkitPro if you prefer) as well as devkitpro on windows and devkitpro on linux.

I think that, rather than specifying the command to install packages, it might be better to link to https://devkitpro.org/wiki/devkitPro_pacman and specify the list. It's pacman on windows, arch, gentoo & fedora but dkp-pacman on debian based systems and macOS.

**Comment by badda71** [comment]
Sorry for the closure - I thought you did not want to follow up.
I received a lot of requests for providing a .cia installation file. This has the advantage that it fully integrates into the 3DS home menu with icon, logo and splash. And it makes starting the homebrew a lot easier (only one click required).
Apart from this, I modified the README.md as per your request.
Getting the autotools ready for building .3dsx would be great - I will check how we can set up an IRC session.

**Comment by badda71** [comment]
I adapted the build system to be closer to your template (and get rid of the bloated buildtools). However, I had to enhance your Makefile in a couple of places to achieve the following:
- .cia/.3ds-build
- support of subdirectories in $SOURCES
- support of sub-projects (e.g. libraries which the main program depends on)

**Comment by badda71** [comment]
*ping*
Ok to close?
