### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by T0biasCZe** [badda71/vice3ds#8]
Sound isnt working on New 2DS XL, tried more roms (tape roms, t64, d64)

**Comment by badda71** [comment]
Have you tried switching to a different sound engine? For New 2DS XL, reSID should be the default engine. Does fastSID work?

**Comment by T0biasCZe** [comment]
No. Also when i check "Sound" in Sound settings, popup with error apear...
edit: after unchecking popup, the "Sound" in settings uncheck
![obrazek](https://user-images.githubusercontent.com/44525446/66591205-b53df580-eb92-11e9-89b7-6c5e03a34c5d.png)

edit2: if i check Sound and set driver to dummy, no error apear but sound still doesnt work ...

**Comment by badda71** [comment]
Did you follow the installation instructions?
-> Apart from this, a DSP-dump is required for sound to work correctly.
https://gbatemp.net/threads/dsp1-a-new-dsp-dumper-cia-for-better-stability.469461/
