### ISSUE TITLE
“Return” key ignored

### ISSUE THREAD

**Issue by MarioKartFan** [badda71/vice3ds#9]
@badda71 Using the latest betas, if I pull up the on-screen keyboard and press the “Return” key, that input is ignored.  If I press the shortcut icon for “Return” it registers just fine.

**Comment by badda71** [comment]
I cannot reproduce the issue. Maybe your "Return" key is mapped to something. Please reset your configuration by deleting the /3ds/vice3ds/config directory on your SD card and check if the issue is still there ...
